[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
